### ISSUE TITLE
State wrong after reboot

### ISSUE THREAD

**Issue by martinhoess** [fredck/lightener#4]
Thank you for this integration, its really useful.

The only "problem" I've found is that after a reboot the state is wrong

![image](https://user-images.githubusercontent.com/47973549/236336330-e321c3d6-e6b3-4577-a31b-4aac5c2f3147.png)

if I set it to 50% and then reboot HA the state always will be 100%.

**Comment by fredck** [comment]
That's a curious one because unlike "real" devices, we're not able to retrieve the state of a Lightener light on startup since the device doesn't physically exist.

It should be reasonable to store the brightness level on shutdown and restore it on start as the default (now we default to 100%). We just don't have a clear place to persist data for our virtual devices but this should be doable in the near future once we introduce config entries with #2.

**Comment by martinhoess** [comment]
Yes, either save before the reboot or recalculate after the reboot on the basis of the current/restored values.
But for this you would have to have a point after the reboot when all other lights are loaded.

**Comment by fredck** [comment]
@martinhoess, I've just released [v2.1.0](https://github.com/fredck/lightener/releases/tag/v2.1.0) with a totally different way to updated the brightness of Lightener lights, now based on the current state of the controlled lights. It should, therefore, not enforce any initial brightness level after reboot.

Can you give it a try and see if this issue is solved? Thanks!
