### ISSUE TITLE
When color temperature is set all lights turn on

### ISSUE THREAD

**Issue by haberda** [fredck/lightener#58]
As the title suggests if you set the color temperature or RGB color of a lightener light it turns all of the lights in the group on regardless of the brightness level. This breaks the functionality when using a lightener light in automatons if color is set or other integrations like adaptive lighting.

**Comment by fredck** [comment]
Can you give step by step details on how to reproduce this? Is it maybe related to #41?

**Comment by haberda** [comment]
I don't think it's related to #41.

I have a lightener light that has three lights. One is a simple on/off light, no brightness. One is an RGBW bulb, and one is a WLED light strip. I have it setup so at the brightest all lights are on, but below 90% the on/off light turns off.  The RGBW light is set to turn off below 20% brightness. This works fine if all I do is set the brightness on the lightener light. 

However, the lightener light has options to set RGB color and color temperature because of the mixed nature of the light group. If color temperature or RGB color is chosen then all lights are turned on regardless of the brightness level. What I would expect is setting the color would only change the lights that are on and capable of setting color.

**Comment by fredck** [comment]
> If color temperature or RGB color is chosen then all lights are turned on

Still a clarification... when you say the above, do you mean that all lights are *off* when you chose the RGB color?

Which TC applies to the issue:

TC1:
 1. Set brightness level in Lightener to 10% -> WLED goes on only at 10%
 2.  Turn all lights off
 3. Chose a RGB color in Lightener -> all controlled lights go on

TC2:
 1. Set brightness level in Lightener to 10% -> WLED goes on only at 10%
 2. Chose a RGB color in Lightener -> all controlled lights go on

TC3:
 1. Restart HA and do not touch any light.
 3. Chose a RGB color in Lightener -> all controlled lights go on

Thanks!

**Comment by haberda** [comment]
With the release of v2.2.2 this no longer appears to be an issue.

**Comment by jamestalbot3** [comment]
@fredck 
I seem to be having this issue still. I use Lightener in combination with [Adaptive Lighting](https://github.com/basnijholt/adaptive-lighting) to mimic Lutron/Ketra setups I do for clients. Natural lighting that changes through the day and different brightness levels for different lights. My main keypad is set to Toggle my lightener device (which is also the only device that Adaptive lighting controls). One of my lightener controlled lights are my overhead lights on a dimmer. These are lights that only support dimming, no white balance, etc.

When I toggle my light via the keypad, every single light turns on no matter what I use as the config for the overhead entity in lightener. If I change the brightness via the web interface for home assistant, lightener immediately turns it off. I'm not sure if this has something to do with color temperature because if I use the temperature slider on the light card tied to my lightener entity it doesn't turn it on/off. I'm still learning Home Assistant, so I'm not sure how best to show logic/programming/automations to help debug, but please let me know if you can help at all.

**Comment by fredck** [comment]
@jamestalbot3, I assume you're calling the "turn_on" service when you use the keypad. If you pas just "on" to Lightener, it doesn't have enough information to understand what you want to do, so, like a light group, it simply turns the lights on.

If you instead call the "turn_on" service telling which brightness level Lightener should be, then the lights will most probably be controlled as you expect.

Please give it a try and let me know if I got it wrong. Thanks!
